FishMarket/FishMarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('novapost/', include('novapost.urls', namespace='novapost')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FishMarket/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart-view'),
    path('add', views.cart_add, name='cart-add'),
    path('delete', views.cart_del, name='cart-delete'),
]

FishMarket/checkout/urls.py
from django.urls import path
from checkout import views

app_name = 'checkout'

urlpatterns = [
    path('', views.checkout, name='checkout'),
    path('successful/', views.checkout_success, name='checkout_success'),
]

FishMarket/novapost/urls.py
from django.urls import path
from novapost import views

app_name = 'novapost'

urlpatterns = [
    path('db/get_city/', views.get_city, name='get_city'),
    path('db/get_warehouses', views.get_warehouses, name='get_warehouses'),
]

FishMarket/users/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from FishMarket.helpers import user_not_authenticated
from .forms import CustomAuthenticationForm, UserPasswordChangeForm, CustomPasswordResetForm, CustomSetPasswordForm
from .views import UserView, signup, user_addresses, user_order_history, email_confirmed, \
    email_confirmation, user_profile_email_confirm, email_send_repeat

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html',
                                                authentication_form=CustomAuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),
    path('profile/', login_required(UserView.as_view()), name='profile'),
    path('signup/', signup, name='signup'),
    path('profile/addresses/', user_addresses, name='user_addresses'),
    path('profile/history/', user_order_history, name='user_history'),
    path('profile/confirm-email/', user_profile_email_confirm, name='user_create_confirm'),
    path('password-change/', login_required(PasswordChangeView.as_view(form_class=UserPasswordChangeForm,
                                                                       success_url=reverse_lazy(
                                                                           "users:password_change_done"),
                                                                       template_name=
                                                                       "users/password_change_form.html")),
         name='password_change'),
    path('password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/', user_not_authenticated(auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                                 email_template_name='users/password_reset_email.html',
                                                                 form_class=CustomPasswordResetForm,
                                                                 success_url=reverse_lazy(
                                                                     "users:password_reset_done"),
                                                                 )),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                     success_url=reverse_lazy('users:password_reset_complete'),
                                                     form_class=CustomSetPasswordForm),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('email-comfirm/', email_confirmation, name='email_confirm'),
    path('email-confirmed/<token>/', email_confirmed, name='email-confirmed'),
    path('profile-confirm-email/', email_send_repeat, name='send-user-confirm-again'),

]

FishMarket/checkout/models.py
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import SET_DEFAULT

from mainapp.models import Product
from users.models import User, NovaAddresses, GuestShopper


class Order(models.Model):
    """Model of Order. Created order."""
    class DeliveryOptions(models.TextChoices):
        pending = "1", "Обробляється"
        shipped = "2", "Відправлено"
        completed = "3", "Завершено"
        cancelled = "4", "Скасовано"

    PAYMENT_CHOICES = [
        ('1', 'Готівка при отриманні'),
        ('2', 'Оплата на картку')
    ]

    user = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=None, null=True, blank=True)
    guest = models.ForeignKey(GuestShopper, on_delete=models.CASCADE, default=None, null=True, blank=True)
    delivery_address = models.CharField(max_length=255, null=True, blank=True, verbose_name='Адрес Доставки')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    status = models.CharField(max_length=1, choices=DeliveryOptions.choices, default=DeliveryOptions.pending, verbose_name='Статус Заказа')
    payment_method = models.CharField(blank=False, null=False , max_length=1, choices=PAYMENT_CHOICES, verbose_name='Метод оплаты')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    cart_total = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True, verbose_name='Сумма за все товары')

    def save(self, *args, **kwargs):
        if self.status == '3' and self.user:
            if self.user.discount < 15:
                discount_amount = (self.cart_total * Decimal(0.05)) / 100
                user_discount = self.user.discount + discount_amount

                if user_discount > 15:
                    self.user.discount = 15
                else:
                    self.user.discount += discount_amount

                self.user.save()
        return super().save(*args, **kwargs)


    def clean(self):
        """Should be a user data for creating an order"""
        if not self.user and not self.guest:
            raise ValidationError("У замовленні має бути або користувач, або гість.")

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ['-created_at']

    def __str__(self):
        if self.user:
            return f"Заказ {self.id} Пользователь: {self.user.phone_number}"
        elif self.guest:
            return f"Заказ {self.id} Гость: {self.guest.phone_number}"

class OrderItem(models.Model):
    """Model of Order Items. There is full information about the order item"""
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items')
    product = models.ForeignKey(Product, on_delete=models.SET_DEFAULT, default=None, verbose_name='Продукт')
    quantity = models.IntegerField(null=True, blank=True, verbose_name='Количество')
    weight = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True, verbose_name='Выбранный вес')
    total_price = models.DecimalField(max_digits=15, decimal_places=2, null=False, blank=False, verbose_name='Сумма за товар')

    def clean(self):
        """Customer should choose (buying by quantity that is set or by their chosen weight"""
        if not self.quantity and not self.weight:
            raise ValidationError('Необхідна кількість (quantity) або вага (weight)')

FishMarket/checkout/forms.py
from django import forms
from django.core.exceptions import ValidationError


class CheckoutUserForm(forms.Form):
    CHOICES = [
        ('1', 'Відділення'),
        ('2', 'Поштомат'),
        ('3', "Кур'єр")
    ]

    CHOICES2 = [
        ('1', 'Готівка при отриманні'),
        ('2', 'Оплата на картку')
    ]

    name = forms.CharField(label="Ім'я",
                           widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ім\'я'}))
    last_name = forms.CharField(label="Прізвище",
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Прізвище'}))
    phone = forms.CharField(label="Телефон", widget=forms.TextInput(
        attrs={'class': 'form-control', 'id': 'phonenumber', 'placeholder': "+38(000)-000-00-00"}))
    delivery_type = forms.ChoiceField(required=False, widget=forms.RadioSelect(
        attrs={'class': 'radio-input', 'id': 'typeOfDelivery'}), choices=CHOICES)
    payment_type = forms.ChoiceField(required=True, widget=forms.RadioSelect(
        attrs={'class': 'radio-payment-choose', 'id': 'paymentType'}), choices=CHOICES2)
    user_address = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'id': 'user_address'}))
    address_from_memory = forms.BooleanField(required=False, initial=False, widget=forms.CheckboxInput(
        attrs={'id': 'userAddressFromMemory', 'style': 'display: none;'}))

    def clean(self):
        cleaned_data = super().clean()

        user_address = cleaned_data.get('user_address')
        delivery_type = cleaned_data.get('delivery_type')
        address_from_memory = cleaned_data.get('address_from_memory')

        if address_from_memory and delivery_type:
            raise ValidationError('Необхідно вибрати лише одну адресу доставки')

        if not user_address:
            raise ValidationError('Виберіть тип доставки')


        return cleaned_data

FishMarket/checkout/views.py
from django.shortcuts import render, redirect

from FishMarket.helpers import check_user_cart
from checkout.forms import CheckoutUserForm
from checkout.order import create_order

@check_user_cart
def checkout(request):
    """
    View for creating an order to db
    Also, update user information while creating an order.
    """

    if request.method == 'GET':
        if request.user.is_authenticated:
            data = {
                'name': request.user.name,
                'last_name': request.user.last_name,
                'phone': request.user.phone_number,
            }
            form = CheckoutUserForm(initial=data)
        else:
            form = CheckoutUserForm()

    if request.method == 'POST':
        form = CheckoutUserForm(request.POST)

        if request.user.is_authenticated:
            user = request.user
            if not all([user.name, user.last_name, user.phone_number]):
                user.name = request.POST.get('name')
                user.last_name = request.POST.get('last_name')
                user.phone_number = request.POST.get('phone')
                user.save()


        if form.is_valid():
            cleaned_data = form.cleaned_data
            cleaned_data['request'] = request
            order_creating = create_order(cleaned_data)

            if order_creating:
                return redirect('checkout:checkout_success')



    return render(request, 'checkout/checkout.html', context={'form': form})

def checkout_success(request):
    """Success page for checkout"""
    return render(request, 'checkout/successful.html')

FishMarket/checkout/templates/checkout/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/form-control.css' %}">
    <script src="https://unpkg.com/imask"></script>
{% endblock %}
{% block robots_follow %}noindex, nofollow{% endblock %}

{% block section %}
    <p class="blue-bold-text">Оформлення замовлення</p>
    {% if not user.is_authenticated %}
        <div class="checkout-register-ads">
            <p>Зареєструйтесь, і після першого замовлення поля заповнюватимуться автоматично.</p>
            <a class="btn" href="{% url 'users:login' %}">Авторизуватися</a>
        </div>
    {% endif %}
    <section class="checkout-section">
        <div class="checkout-container">
            <form id="FormCheckout" class="form-checkout" method="POST">
                {% csrf_token %}
                {{ form.warehouse_number }}
                <div class="checkout-form">
                    <div class="checkout-form-title">
                        <span class="check-form-title-number">1</span>
                        <p class="blue-bold-md">Контактні дані</p>
                    </div>
                    <div class="form-group">
                        {% if form.name.errors %}
                            <ul class="error-list">
                                {% for error in form.name.errors %}
                                    <li class="error-item">{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <div class>
                            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}<span
                                    class="important-red">*</span></label>
                            {{ form.name }}
                        </div>
                        {% if form.last_name.errors %}
                            <ul class="error-list">
                                {% for error in form.last_name.errors %}
                                    <li class="error-item">{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <div>
                            <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}<span
                                    class="important-red">*</span></label>
                            {{ form.last_name }}
                        </div>
                        {% if form.phone.errors %}
                            <ul class="error-list">
                                {% for error in form.phone.errors %}
                                    <li class="error-item">{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <div>
                            <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}<span
                                    class="important-red">*</span></label>
                            {{ form.phone }}
                        </div>
                    </div>
                </div>
                <div class="checkout-form">
                    <div class="checkout-form-title">
                        <span class="check-form-title-number">2</span>
                        <p class="blue-bold-md">Доставка</p>
                    </div>
                    {% if form.errors %}
                        {% if form.non_field_errors %}
                            <div class="error-list">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                    {% endif %}
                    <div class="form-group delivery-choice-group">
                        {% if user.is_authenticated %}
                            {% if user.nova_addresses.exists %}
                                {{ form.address_from_memory }}
                                <button type="button"
                                        onclick="document.getElementsByClassName('novaposhta-users-addresses')[0].style.display='flex';"
                                        id="UsersAddressesButton"
                                        class="white-container user-delivery-container">
                                    <img class="history-addresses"
                                         src="{% static 'checkout/img/history-addresses.png' %}"
                                         alt="Ваши сохраненные адреса картинка">
                                    <p class="text-grey">Вибрати зі збережених адрес</p>

                                    <div class="button-img-container">

                                    </div>
                                </button>
                            {% endif %}
                        {% endif %}
                        {{ form.delivery_type }}
                        <button disabled
                                onclick="document.getElementsByClassName('novaposhta-container')[0].style.display='flex';"
                                type="button" id="novaposhta-button"
                                class="white-container user-delivery-container blured-div">
                            <img class="history-addresses" src="{% static 'checkout/img/nova_poshta_icon.webp' %}"
                                 alt="">
                            <p class="text-grey">Вибрати спосіб доставки</p>
                            <div class="button-img-container">

                            </div>
                        </button>
                    </div>
                </div>
                <div class="checkout-form">
                    <div class="checkout-form-title">
                        <span class="check-form-title-number">3</span>
                        <p class="blue-bold-md">Оплата</p>
                    </div>
                    {% if form.payment_type.errors %}
                        {% for error in  form.payment.errors %}
                            <ul>
                                <li class="error-list">
                                    {{ error }}
                                </li>
                            </ul>
                        {% endfor %}
                    {% endif %}
                    <div class="payment-radio">
                        {{ form.payment_type }}
                    </div>
                </div>
                {{ form.user_address }}
            </form>
        </div>

        {% include 'checkout/includes/right-container.html' %}

        <div class="novaposhta-container">
            <div class="novaposhta-window white-container">
                <div class="novaposhta-window-title">
                    <p class="blue-bold-text novaposhta-window-title-change">Вибрати відділення</p>
                    <button class="window-button-close"
                            onclick="document.getElementsByClassName('novaposhta-container')[0].style.display='none';">
                        <img class="close-window-title" src="{% static 'checkout/img/close_blue.png' %}" alt="">
                    </button>
                </div>
                <div class="novaposhta-window-content">
                    <div id="novaposhta-input-courier" class="novaposhtaFormCourier hidden-field">
                        <label for="courier-field-city">Місто <span class="important-red">*</span></label>
                        <input type="search" id="courier-field-city" placeholder="Введіть місто"/>
                        <label for="courier-field-street">Вулиця <span class="important-red">*</span></label>
                        <input type="search" id="courier-field-street" placeholder="Введіть вулицю"/>
                        <label for="courier-field-house">Будинок <span class="important-red">*</span></label>
                        <input type="search" id="courier-field-house" placeholder="Введіть номер будинку"/>
                        <label for="courier-field-apartment">Квартира</label>
                        <input type="search" id="courier-field-apartment" placeholder="Введіть квартиру"/>
                        <button
                                disabled
                                id="AwakeButtonCourier"
                                class="btn blured-div"
                                onclick="courierButtonSubmit()"
                        >
                            Підтвердити
                        </button>
                    </div>
                    <div id="CitySearth-ware" class="novaposhta-input">
                        <img src="{% static 'checkout/img/search_cbd5e1.png' %}" alt="">
                        <input type="search" id="city-search" placeholder="Введіть місто або населений пункт"/>
                    </div>
                    <div id="warehouse-searchID" class="novaposhta-input hidden-field">
                        <img src="{% static 'checkout/img/search_cbd5e1.png' %}" alt="">
                        <input type="search" id="warehouse-search" placeholder="Введіть номер відділення або адресу"/>
                    </div>
                    <div class="novaposhta-output-city">
                        <div class="swiper swiper2">
                            <div class="swiper-wrapper swiper-items swiper-novaposhta-output">

                            </div>
                            <div class="swiper-scrollbar"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="novaposhta-users-addresses">
            <div class="novaposhta-window white-container">
                <div class="novaposhta-window-title">
                    <p class="blue-bold-text novaposhta-window-title-change">Збережені адреси</p>
                    <button class="window-button-close"
                            onclick="document.getElementsByClassName('novaposhta-users-addresses')[0].style.display='none';">
                        <img class="close-window-title" src="{% static 'checkout/img/close_blue.png' %}" alt="">
                    </button>
                </div>
                <div class="user-output-addresses">
                    <div class="swiper swiper3">
                        <div class="swiper-wrapper swiper-items">
                            {% for address in user.nova_addresses.all %}
                                <div class="swiper-slide">
                                    <div class="option-item">
                                        <div class="option-info-text">
                                            <p class="option-text-title">
                                                <span class="option-text-title-span">{{ address.delivery_address|title }}</span>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="swiper-scrollbar"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        const novapost_city = "{% url 'novapost:get_city' %}";
        const novapost_warehouses = "{% url 'novapost:get_warehouses' %}"
        const csrf = "{{ csrf_token }}"
    </script>
    <script src="{% static 'checkout/js/checkout.js' %}"></script>
    {% if not user.is_email_confirmed %}
    <div class="email-verify-warning">
        <div class="email-div white-container">
            <p class="blue-bold-md">Для створення замовлення пошта має бути підтверджена</p>
            <a class="btn" href="{% url 'users:send-user-confirm-again' %}">Підтвердити</a>
            <a class="btn btn-grey" href="{% url 'cart:cart-view' %}">Назад</a>
        </div>
    </div>
    {% endif %}
{% endblock %}

FishMarket/checkout/templates/checkout/successful.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'checkout/css/successful.css' %}">
{% endblock %}
{% block robots_follow %}noindex, nofollow{% endblock %}

{% block section %}
    <section class="successful-div">
        <img src="{% static 'checkout/img/succesful.png' %}" alt="Дякуємо за ваше замовлення">
        <h3>Дякуємо за ваше замовлення!</h3>
        <p>Вашу заявку буде оброблено найближчим часом! Якщо у Вас залишилися запитання, напишіть нам із зазначенням
            прізвища для швидшої обробки замовлення</p>
    </section>
    <h3 class="contact-container-title">Контакти</h3>
    <section class="contact-container">

        <ul class="contacts">
            <li>
                <img src="{% static 'checkout/img/mail.png' %}" alt="почта">
                <a href="mailto:testtest@gmail.com?subject=Техническая%20поддержка">testtest@gmail.com</a>
            </li>
            <li>
                <img src="{% static 'checkout/img/telegram.png' %}" alt="telegram">
                <a href="https://t.me/test">Telegram</a>
            </li>
            <li>
                <img src="{% static 'checkout/img/calls.png' %}" alt="call">
                <a href="tel:+380988811617">+380988811617</a>
            </li>
        </ul>
        <ul class="contacts-info">
            <li>
                <h4>Обробляємо замовлення:</h4>
                <p>Понеділок - неділя з 11:00 до 22:00 (сім днів на тиждень)</p>
            </li>
        </ul>

        <ul class="contacts-info">
            <li>
                <h4>Відправляємо товари з Харкова:</h4>
                <p>Понеділок - Неділя Без вихідних</p>
            </li>
        </ul>
    </section>
{% endblock %}