FishMarket/FishMarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('novapost/', include('novapost.urls', namespace='novapost')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FishMarket/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart-view'),
    path('add', views.cart_add, name='cart-add'),
    path('delete', views.cart_del, name='cart-delete'),
]

FishMarket/users/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from FishMarket.helpers import user_not_authenticated
from .forms import CustomAuthenticationForm, UserPasswordChangeForm, CustomPasswordResetForm, CustomSetPasswordForm
from .views import UserView, signup, user_addresses, user_order_history, email_confirmed, \
    email_confirmation, user_profile_email_confirm, email_send_repeat

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html',
                                                authentication_form=CustomAuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),
    path('profile/', login_required(UserView.as_view()), name='profile'),
    path('signup/', signup, name='signup'),
    path('profile/addresses/', user_addresses, name='user_addresses'),
    path('profile/history/', user_order_history, name='user_history'),
    path('profile/confirm-email/', user_profile_email_confirm, name='user_create_confirm'),
    path('password-change/', login_required(PasswordChangeView.as_view(form_class=UserPasswordChangeForm,
                                                                       success_url=reverse_lazy(
                                                                           "users:password_change_done"),
                                                                       template_name=
                                                                       "users/password_change_form.html")),
         name='password_change'),
    path('password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/', user_not_authenticated(auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                                 email_template_name='users/password_reset_email.html',
                                                                 form_class=CustomPasswordResetForm,
                                                                 success_url=reverse_lazy(
                                                                     "users:password_reset_done"),
                                                                 )),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                     success_url=reverse_lazy('users:password_reset_complete'),
                                                     form_class=CustomSetPasswordForm),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('email-comfirm/', email_confirmation, name='email_confirm'),
    path('email-confirmed/<token>/', email_confirmed, name='email-confirmed'),
    path('profile-confirm-email/', email_send_repeat, name='send-user-confirm-again'),

]

FishMarket/users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.core.validators import MinLengthValidator


class UserManager(BaseUserManager):

    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError('Користувач повинен мати адресу електронної пошти')
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        user = self._create_user(email, password, True, True, **extra_fields)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=100, unique=True, verbose_name='Електронна пошта')
    name = models.CharField(max_length=25, null=True, blank=True, verbose_name="Ім'я")
    last_name = models.CharField(max_length=25, null=True, blank=True, verbose_name='Прізвище')
    discount = models.DecimalField(max_digits=4, decimal_places=2, null=True, default=0, verbose_name='Знижка (%)')
    is_staff = models.BooleanField(default=False, verbose_name='Співробітник')
    is_superuser = models.BooleanField(default=False, verbose_name='Власник')
    is_active = models.BooleanField(default=True, verbose_name='Активний')
    last_login = models.DateTimeField(null=True, blank=True, verbose_name='Останній вхід')
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')
    is_email_confirmed = models.BooleanField(default=False, verbose_name='Підтверджено електронну пошту')
    phone_number = models.CharField(validators=[MinLengthValidator(8)], max_length=18, null=True, blank=True,
                                    verbose_name='Номер телефону')

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self):
        return "/users/%i/" % (self.pk)

    class Meta:
        verbose_name = 'Користувач'
        verbose_name_plural = 'Користувачі'


class NovaAddresses(models.Model):
    class DeliveryOptions(models.TextChoices):
        nova_branch = "1", "Відділення"
        parcel_box = "2", "Поштомат"
        courier = "3", "Кур'єр"

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True ,related_name='nova_addresses')
    delivery_choice = models.CharField(max_length=1, choices=DeliveryOptions.choices, blank=False, null=False, verbose_name='Тип доставки')
    delivery_address = models.CharField(null=True, blank=True, max_length=255, verbose_name='Адрес доставки')

    class Meta:
        verbose_name = 'Адрес Novaposhta'
        verbose_name_plural = 'Адресы Novaposhta'

    def __str__(self):
        return self.delivery_address


class GuestShopper(models.Model):
    name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    phone_number = models.CharField(validators=[MinLengthValidator(8)], max_length=18, null=False, blank=False)

FishMarket/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, PasswordResetForm, \
    SetPasswordForm
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation
from django import forms

from .models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = 'Поштова адреса'
        self.fields['password1'].label = 'Пароль'
        self.fields['password2'].label = 'Підтвердження пароля'

        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введіть вашу пошту @',
        })
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введіть пароль',
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введіть пароль повторно',
        })

    def clean_email(self):
        email = self.cleaned_data['email']
        email = email.lower()
        return email


class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request=request, *args, **kwargs)
        self.fields['username'].label = ''
        self.fields['password'].label = ''

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введіть вашу пошту @',
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введіть пароль',
        })

    def clean_username(self):
        username = self.cleaned_data['username']

        if '@' not in username:
            raise ValidationError('Потрібно вказати повну поштову адресу ___@__.__')
        elif '.' not in username:
            raise ValidationError('Потрібно вказати повну поштову адресу ___@__.__')

        username = username.lower()
        return username


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старий Пароль', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Старий Пароль'}))
    new_password1 = forms.CharField(label='Новий пароль', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Новий пароль'}))
    new_password2 = forms.CharField(label='Новий пароль', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Новий пароль 2'}))

    def __init__(self, user, *args, **kwargs):
        super().__init__(user, *args, **kwargs)
        self.fields['old_password'].label = ''
        self.fields['new_password1'].label = ''
        self.fields['new_password2'].label = ''

class CustomPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = ''
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введіть вашу пошту @',
        })

class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].label = ''
        self.fields['new_password2'].label = ''

        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Пароль 1',
        })
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Повторно Пароль',
        })

class UserChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('name', 'last_name', 'email', 'phone_number')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Ім'я"}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Прізвище:'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Електронна пошта:'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control', 'id': 'phonenumber', 'placeholder': "+38(000)-000-00-00"}),
        }

FishMarket/users/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Prefetch
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from FishMarket.helpers import user_not_authenticated, user_email_confirmed
from checkout.models import Order, OrderItem
from .forms import SignUpForm
from .helpers import email_sender, user_email_activator
from .models import User, NovaAddresses
from .forms import UserChangeForm


class UserView(UpdateView):
    model = User
    template_name = 'users/profile.html'
    form_class = UserChangeForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

@user_not_authenticated
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(request, email=user.email, password=raw_password)

            if user is not None:
                login(request, user)
                if not user.is_email_confirmed:
                    email_sender(request, user)
                    return redirect('users:email_confirm')

                return redirect('users:profile')
    else:
        form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form})

@user_email_confirmed
def email_send_repeat(request):
    email_sender(request, request.user)
    return redirect('users:email_confirm')

@user_email_confirmed
def email_confirmation(request):
    return render(request, 'users/email_sent.html')


def email_confirmed(request, token):
    tk_confirm = user_email_activator(token)

    if tk_confirm:
        return render(request, 'users/email_confirmed.html')
    else:
        return redirect('users:user_create_confirm')

@user_email_confirmed
def user_profile_email_confirm(request):
    return render(request, 'users/user_confirm_email.html')

def user_addresses(request):
    user_addresses = NovaAddresses.objects.filter(user=request.user)

    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        if address_id:
            NovaAddresses.objects.get(user=request.user, id=address_id).delete()

    return render(request, 'users/user_addresses.html', context={'user_addresses': user_addresses})


def user_order_history(request):
    orders = Order.objects.filter(user=request.user).prefetch_related(
        Prefetch('order_items', queryset=OrderItem.objects.select_related('product')))

    paginator = Paginator(orders, 3)
    page = request.GET.get('page')

    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return render(request, 'users/user_history.html', context={'orders': page_obj, 'page_obj': page_obj})

FishMarket/users/templates/users/email_confirmed.html
{% extends 'base.html' %}
{% block title %}Вашу пошту підтверджено{% endblock %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'checkout/css/successful.css' %}">
{% endblock %}

{% block section %}
    <section class="successful-div">
        <img src="{% static 'checkout/img/succesful.png' %}" alt="Адреса підтверджена">
        <h3>Адреса підтверджена!</h3>
    </section>
{% endblock %}

FishMarket/users/templates/users/email_sent.html
{% extends 'base.html' %}
{% block title %}Лист надіслано!{% endblock %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'checkout/css/successful.css' %}">
{% endblock %}

{% block section %}
    <section class="successful-div">
        <img src="{% static 'users/img/mark_email_unread.png' %}" alt="Лист надіслано">
        <h3>Підтвердження поштової адреси</h3>
        <p>Лист надіслано, підтвердьте ваш email (не забудьте перевірити папку зі спамом, якщо листа немає)</p>
    </section>
{% endblock %}

FishMarket/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block robots_follow %}noindex, nofollow{% endblock %}

{% block title %}Вхід до особистого кабінету{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static '/css/login.css' %}">
{% endblock %}
{% block section %}
    <div class="login-page">
        <div class="login-box">
            <h3>Вхід</h3>
            <form class="login-form" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <br>
                <div class="login-box-menu">
                    <button class="submit-button" type="submit">Вхід</button>
                    <a class="restore-password" href="{% url 'users:password_reset' %}">Забули свій пароль?</a>
                </div>
            </form>
        </div>
        <div class="open-door">
            <img src="{% static 'users/img/open-door1.png' %}" alt="log-in-separator">
        </div>
        <div class="information-box">
            <h3>Новий Користувач?</h3>
            <p>Створення облікового запису дозволить вам здійснювати покупки швидше (адресу та контактну інформацію не
                потрібно буде вводити повторно), переглядати стан замовлення, а також бачити історію попередніх
                замовлень.
                Ви також зможете накопичувати знижки та спеціальні пропозиції.</p>
            <a href="{% url 'users:signup' %}" class="submit-button">Реєстрація</a>

        </div>
    </div>

{% endblock %}

FishMarket/users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% load static %}
{% block robots_follow %}noindex, nofollow{% endblock %}
{% block title %}Пароль змінено!{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/password_change_done.css' %}">{% endblock %}

{% block section %}
    <div class="container">
        <h3>Пароль змінено</h3>
        <a href="{% url 'users:profile' %}">Назад</a>
    </div>
{% endblock %}

FishMarket/users/templates/users/password_change_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}<link rel="stylesheet" href="{% static "css/password_reset.css" %}">{% endblock %}
{% block robots_follow %}noindex, nofollow{% endblock %}
{% block title %}Зміна пароля{% endblock %}

{% block section %}
    <section>
        <div class="container">
            <a href="{% url 'users:profile' %}">Назад</a>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Змінити пароль</button>
            </form>
        </div>
    </section>
{% endblock %}

FishMarket/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}
{% block robots_follow %}noindex, nofollow{% endblock %}
{% block title %}Скидання пароля{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/password_reset.css' %}">{% endblock %}

{% block section %}
    <div class="container">
        <h3 class="success-alert">Пароль змінено</h3>
        <a class="btn-btn-btn" href="{% url 'users:login' %}">Вхід</a>
    </div>
{% endblock %}

FishMarket/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/password_reset.css' %}">{% endblock %}
{% block robots_follow %}noindex, nofollow{% endblock %}
{% block title %}Підтвердження зміни пароля{% endblock %}

{% block section %}
    <section>
        <div class="container">
            {% for field in form %}
                {% if field.errors %}
                    <div class="text-danger">
                        <ul>
                            {% for error in field.errors %}
                                <li><p>{{ error }}</p></li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            {% endfor %}
            <form method="POST">
                {% csrf_token %}
                {{ form.new_password1 }}
                {{ form.new_password2 }}
                <button type="submit">Змінити</button>
            </form>
        </div>
    </section>
{% endblock %}

FishMarket/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}
{% block robots_follow %}noindex, nofollow{% endblock %}
{% block title %}Пароль змінено!{% endblock %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'checkout/css/successful.css' %}">
{% endblock %}

{% block section %}
    <section class="successful-div">
        <img src="{% static 'checkout/img/succesful.png' %}" alt="Пароль сброшен.">
        <h3>Сброс пароля</h3>
        <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
        <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
    </section>
{% endblock %}

FishMarket/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
    {% blocktranslate %}You're receiving this email because you requested a password reset for your user account at
        {{ site_name }}.{% endblocktranslate %}

    {% translate "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}
    {% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

    {% translate "Thanks for using our site!" %}

    {% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

FishMarket/users/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}<link rel="stylesheet" href="{% static 'css/password_reset.css' %}">{% endblock %}
{% block robots_follow %}noindex, nofollow{% endblock %}
{% block title %}Зміна пароля! Не поспішайте:){% endblock %}
{% block section %}
    <section>
        <div class="container">
            <h3>Восстановление Пароля</h3>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Продовжити</button>
            </form>
        </div>
    </section>
{% endblock %}

FishMarket/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/form-control.css' %}">
    <script src="https://unpkg.com/imask"></script>
{% endblock %}
{% block robots_follow %}noindex, nofollow{% endblock %}
{% block title %}Профіль користувача {{ user.name }}{% endblock %}

{% block section %}
    <section>
        <ul class="profile-elems">
            <li class="menu-elem">
                <ul>
                    <li class="active-link">
                        <img src="{% static 'users/img/settings-profile.png' %}" alt="profile icon">
                        <a href="{% url 'users:profile' %}">Профіль</a>
                    </li>
                    <li>
                        <img src="{% static 'img/history.png' %}" alt="profile icon">
                        <a href="{% url 'users:user_history' %}">Історія замовлень</a>
                    </li>
                    <li>
                        <img src="{% static 'img/address.png' %}" alt="profile icon">
                        <a href="{% url 'users:user_addresses' %}">Адреса доставки</a>
                    </li>
                    <li>
                        <img src="{% static 'users/img/password.png' %}" alt="пароль">
                        <a href="{% url 'users:password_change' %}">Змінити пароль</a>
                    </li>
                    {% if not user.is_email_confirmed %}
                        <li>
                            <img src="{% static 'users/img/mail_red.png' %}" alt="подтвердить пошту">
                            <a href="{% url 'users:user_create_confirm' %}">Підтвердити пошту</a>
                        </li>
                    {% endif %}
                    <li class="exit-button">
                        <img src="{% static 'users/img/exit.png' %}" alt="выхiд з аккаунту">
                        <a class='a-exit' href="{% url 'users:logout' %}">Вийти з кабінету</a>
                    </li>
                </ul>
            </li>
            <li>
                <ul class="profile-menu">
                    <li>
                        <form class="form-user-data" method="POST" action="">
                            <h3 class="blue-bold-text">Моя інформація <br><span
                                    class="span-user-email">{{ user.email }}</span></h3>
                            {% csrf_token %}
                            {% for field in form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% if field.errors %}
                                    <ul class="error-list">
                                        {% for error in field.errors %}
                                            <li class="error-item">{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                                {{ field }}
                            {% endfor %}

                            <button class='btn' type="submit">Обновить</button>
                        </form>
                    </li>
                </ul>
            </li>
            <li>
                <ul class="discount-container">
                    <li class="banner-discount-show">
                        <h3 class="white-bold-text">Моя знижка</h3>
                        <h3 class="span-user-discount">{{ user.discount }}%</h3>
                    </li>
                </ul>
            </li>
            <li>

            </li>
        </ul>
    </section>

    <script>
        const element = document.getElementById('phonenumber');
        const maskOptions = {
            mask: '+{38}(000)-000-00-00'
        };
        const mask = IMask(element, maskOptions);
    </script>

{% endblock %}

FishMarket/users/templates/users/signup.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static '/css/registration.css' %}">
{% endblock %}
{% block robots_follow %}noindex, nofollow{% endblock %}
{% block title %}Вхід в особистий кабінет{% endblock %}
{% block section %}
    <div class="registration-page">
        <h3 class="blue-bold-text">Реєстрація</h3>
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                {{ field.label }}
                <br>
                {{ field }}
                {{ field.errors }}
                <br>
            {% endfor %}
            <button type="submit" class="btn">Реєстрація</button>
        </form>
    </div>
{% endblock %}

FishMarket/users/templates/users/user_confirm_email.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}
{% block robots_follow %}noindex, nofollow{% endblock %}
{% block title %}Надіслати листа підтвердження{% endblock %}

{% block section %}
    <section>
        <ul class="profile-elems">
            <li class="menu-elem">
                <ul>
                    <li>
                        <img src="{% static 'users/img/settings-profile.png' %}" alt="profile icon">
                        <a href="{% url 'users:profile' %}">Профіль</a>
                    </li>
                    <li>
                        <img src="{% static 'img/history.png' %}" alt="profile icon">
                        <a href="{% url 'users:user_history' %}">Історія замовлень</a>
                    </li>
                    <li>
                        <img src="{% static 'img/address.png' %}" alt="profile icon">
                        <a href="{% url 'users:user_addresses' %}">Адреса доставки</a>
                    </li>
                    <li>
                        <img src="{% static 'users/img/password.png' %}" alt="пароль">
                        <a href="{% url 'users:password_change' %}">Змінити пароль</a>
                    </li>
                    <li class="active-link">
                        <img src="{% static 'users/img/mail_red.png' %}" alt="подтвердить пошту">
                        <a href="{% url 'users:user_create_confirm' %}">Підтвердити пошту</a>
                    </li>
                    <li class="exit-button">
                        <img src="{% static 'users/img/exit.png' %}" alt="выхiд з аккаунту">
                        <a class='a-exit' href="{% url 'users:logout' %}">Вийти з кабінету</a>
                    </li>
                </ul>
            </li>
            <li class="email-confirm">
                <p class="blue-bold-text">Надіслати email для підтвердження</p>
                <a class="btn" href="{% url 'users:send-user-confirm-again' %}">Надіслати</a>
            </li>
        </ul>
{% endblock %}