FishMarket/FishMarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('novapost/', include('novapost.urls', namespace='novapost')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FishMarket/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart-view'),
    path('add', views.cart_add, name='cart-add'),
    path('delete', views.cart_del, name='cart-delete'),
]

FishMarket/mainapp/urls.py
from django.urls import path
from mainapp import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='main'),
    path('products/<slug:slug>', views.ProductDetailView.as_view(), name='product'),
    path('categories-all-products/', views.AllProductsOrSpecificView.as_view(), name='AllProducts'),
]

FishMarket/users/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from FishMarket.helpers import user_not_authenticated
from .forms import CustomAuthenticationForm, UserPasswordChangeForm, CustomPasswordResetForm, CustomSetPasswordForm
from .views import UserView, signup, user_addresses, user_order_history, email_confirmed, \
    email_confirmation, user_profile_email_confirm, email_send_repeat

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html',
                                                authentication_form=CustomAuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),
    path('profile/', login_required(UserView.as_view()), name='profile'),
    path('signup/', signup, name='signup'),
    path('profile/addresses/', user_addresses, name='user_addresses'),
    path('profile/history/', user_order_history, name='user_history'),
    path('profile/confirm-email/', user_profile_email_confirm, name='user_create_confirm'),
    path('password-change/', login_required(PasswordChangeView.as_view(form_class=UserPasswordChangeForm,
                                                                       success_url=reverse_lazy(
                                                                           "users:password_change_done"),
                                                                       template_name=
                                                                       "users/password_change_form.html")),
         name='password_change'),
    path('password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/', user_not_authenticated(auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                                 email_template_name='users/password_reset_email.html',
                                                                 form_class=CustomPasswordResetForm,
                                                                 success_url=reverse_lazy(
                                                                     "users:password_reset_done"),
                                                                 )),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                     success_url=reverse_lazy('users:password_reset_complete'),
                                                     form_class=CustomSetPasswordForm),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('email-comfirm/', email_confirmation, name='email_confirm'),
    path('email-confirmed/<token>/', email_confirmed, name='email-confirmed'),
    path('profile-confirm-email/', email_send_repeat, name='send-user-confirm-again'),

]

FishMarket/templates/includes/footer.html
{% load static %}
{% load menu %}

<footer class="page-footer">
    <ul class="page-footer-menu">
        <li>
            <img class="header-logo" src="{% static 'img/logo-banner.png' %}" alt="Logo of Website">
            <p class="footer-text">© DryFishUA. All rights reserved.</p>
        </li>
        <li class="li-footer-phone">
            <p class="footer-text">Оформити замовлення:</p>
            <a href="tel:+380988811617" alt="telephone:+380988811617">+380988811617</a>
        </li>
        <li>
            <p class="footer-text">Час роботи:</p>
            <p class="footer-text">з 11:00 до 22:00</p>
        </li>
        <li>
            <p class="footer-text">Ми в соцмережах:</p>
            <img class="social-media-icons-footer" src="{% static 'img/instagram_logo.png' %}"
                 alt="social media link: instagram">
        </li>
    </ul>
</footer>

FishMarket/templates/includes/header.html
{% load static %}
<header>
    <nav class="">
        <a class="" href="{% url 'mainapp:AllProducts' %}">
            <img class="header-logo" src="{% static 'img/logo-banner.png' %}" alt="Logo">
        </a>
        <ul class="main-menu">
            {% include 'includes/main-menu-desktop.html' %}
            <li>
                <fieldset class="desktop-bucket-button HideOnMobile">
                    {% if cart|length > 0 %}
                        <legend id="bucket-change-quantity" class="desktop-bucket-quantity">{{ cart|length }}</legend>
                    {% endif %}
                    <a class="desktop-bucket" href="{% url 'cart:cart-view' %}"><img
                            src="{% static 'img/shopping_basket.png' %}" alt=""></a>
                </fieldset>
            </li>
            {% if user.is_anonymous %}
                <li>
                    <a href="{% url 'users:login' %}"><img class='nav-img-button' src="{% static 'img/login.png' %}"
                                                           alt=""></a>
                </li>
            {% elif user.is_authenticated %}
                <li class="user-profile">
                    <a href="{% url 'users:profile' %}">
                        <img class='nav-img-button' src="{% static 'img/profile.png' %}" alt="Аккаунт">
                    </a>
                </li>
            {% endif %}
            <li>
                <button class="burger HideOnDesktop"
                        onclick="document.querySelector('.nav-burger').classList.toggle('active');">
                    <img class="nav-img-button" src="{% static 'img/burger-menu.png' %}" alt="">
                </button>

                <div class="nav-burger">
                    <div class="up-menu">
                        <div class="profile">
                            {% if user.is_authenticated %}
                                <a href="{% url 'users:profile' %}"><img src="{% static 'img/profile.png' %}"
                                                                         alt="Профиль"></a>
                            {% else %}
                                <a href="{% url 'users:login' %}"><img src="{% static 'img/login.png' %}"
                                                                       alt="Вход"></a>
                            {% endif %}
                        </div>
                        <div class="close">
                            <button class="burger"
                                    onclick="document.querySelector('.nav-burger').classList.remove('active');">
                                <img src="{% static 'img/close.png' %}" alt="Закрыть">
                            </button>
                        </div>
                    </div>
                    {% include 'includes/main-menu-mobile.html' %}
                </div>
            </li>
        </ul>
    </nav>
</header>

FishMarket/templates/includes/main-menu-desktop.html
{% load categories %}
{% load menu %}
{% navmenu as menu %}
{% load static %}

{% for name, url in menu.items %}
    {% if url.class %}
        <li class="{{ url.class }} HideOnMobile">
            <button class="btn-category"
                    onclick="document.querySelector('.drop-down-category', event.stopPropagation()).style.display = 'flex'">{{ name }}</button>
            <img class="btn-category-dropdown" src="{% static 'img/dropdown.png' %}" alt="">
            <ul class="drop-down-category">
                {% categories as categories_list %}
                {% for category in categories_list %}
                    <li>
                        <a href="{% url 'mainapp:AllProducts' %}?category={{ category.slug }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </li>
    {% else %}
        <li class="HideOnMobile"><a href="{{ url.url }}">{{ name }}</a></li>
    {% endif %}
{% endfor %}

FishMarket/templates/includes/main-menu-mobile.html
{% load menu %}

<ul class="nav-burger-list">
    {% navmenu as menu %}
    {% for name, url in menu.items %}
        <li class="nav-burger-list-item"><a href="{{ url.url }}">{{ name }}</a></li>
    {% endfor %}
    <li class="nav-burger-list-item"><p>Замовлення Пн-Сб з 9:00 до 18:00</p></li>
</ul>

FishMarket/templates/includes/mobile-bucket.html
{% load static %}


{% if cart|length %}
<div class="mobile-bucket-container HideOnDesktop">
    <div class="mobile-bucket-text-image"><a href="{% url 'cart:cart-view' %}">{{ cart|length }}
        тов. {{ cart.get_full_price|floatformat }} грн</a></div>
    <div class="mobile-bucket-text-image"><a href="{% url 'cart:cart-view' %}">Оформити <img
            src="{% static 'img/shopping_basket.png' %}" alt=""></a></div>
</div>
{% endif %}