FishMarket/FishMarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('novapost/', include('novapost.urls', namespace='novapost')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FishMarket/cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart-view'),
    path('add', views.cart_add, name='cart-add'),
    path('delete', views.cart_del, name='cart-delete'),
]

FishMarket/usersapp/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .forms import CustomAuthenticationForm, UserPasswordChangeForm, CustomPasswordResetForm, CustomSetPasswordForm
from .views import UserView, signup

app_name = 'usersapp'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='usersapp/login.html',
                                                authentication_form=CustomAuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),
    path('profile/', login_required(UserView.as_view()), name='profile'),
    path('signup/', signup, name='signup'),
    path('password-change/', login_required(PasswordChangeView.as_view(form_class=UserPasswordChangeForm,
                                                                       success_url=reverse_lazy(
                                                                       "usersapp:password_change_done"),
                                                                       template_name=
                                                                       "usersapp/password_change_form.html")),
                                                                       name='password_change'),
    path('password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='usersapp/password_change_done.html'),
                                                   name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='usersapp/password_reset_form.html',
                                                                 email_template_name='usersapp/password_reset_email.html',
form_class=CustomPasswordResetForm,
                                                                 success_url=reverse_lazy(
                                                                 "usersapp:password_reset_done"),
                                                                 ),
                                                                 name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='usersapp/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='usersapp/password_reset_confirm.html',
                                                     success_url=reverse_lazy('usersapp:password_reset_complete'),
                                                     form_class=CustomSetPasswordForm),
                                                     name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='usersapp/password_reset_complete.html'),
                                                      name='password_reset_complete')
]

FishMarket/usersapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from .forms import SignUpForm
from .models import User
from .forms import UserChangeForm


class UserView(UpdateView):
    model = User
    template_name = 'usersapp/profile.html'
    form_class = UserChangeForm
    success_url = reverse_lazy('usersapp:profile')

    def get_object(self, queryset=None):
        return self.request.user

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(request, email=user.email, password=raw_password)
            if user is not None:
                login(request, user)
            else:
                print("user is not authenticated")
            return redirect('usersapp:profile')
    else:
        form = SignUpForm()
    return render(request, 'usersapp/signup.html', {'form': form})

FishMarket/usersapp/templates/usersapp/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Вхід до особистого кабінету{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static '/css/login.css' %}">
{% endblock %}
{% block section %}
    <div class="login-page">
        <div class="login-box">
            <h3>Вхід</h3>
            <form class="login-form" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <br>
                <div class="login-box-menu">
                    <button class="submit-button" type="submit">Вхід</button>
                    <a class="restore-password" href="{% url 'usersapp:password_reset' %}">Забули свій пароль?</a>
                </div>
            </form>
        </div>
        <div class="open-door">
            <img src="{% static 'usersapp/img/open-door1.png' %}" alt="log-in-separator">
        </div>
        <div class="information-box">
            <h3>Новий Користувач?</h3>
            <p>Створення облікового запису дозволить вам здійснювати покупки швидше (адресу та контактну інформацію не
                потрібно буде вводити повторно), переглядати стан замовлення, а також бачити історію попередніх
                замовлень.
                Ви також зможете накопичувати знижки та спеціальні пропозиції.</p>
            <a href="{% url 'usersapp:signup' %}" class="submit-button">Реєстрація</a>

        </div>
    </div>

{% endblock %}

FishMarket/usersapp/templates/usersapp/password_change_done.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/password_change_done.css' %}">{% endblock %}

{% block section %}
    <div class="container">
        <h3>Пароль змінено</h3>
        <a href="{% url 'usersapp:profile' %}">Назад</a>
    </div>
{% endblock %}

FishMarket/usersapp/templates/usersapp/password_change_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}<link rel="stylesheet" href="{% static "css/password_reset.css" %}">{% endblock %}

{% block section %}
    <section>
        <div class="container">
            <a href="{% url 'usersapp:profile' %}">Назад</a>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Змінити пароль</button>
            </form>
        </div>
    </section>
{% endblock %}

FishMarket/usersapp/templates/usersapp/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/password_reset.css' %}">{% endblock %}

{% block section %}
    <div class="container">
        <h3 class="success-alert">Пароль змінено</h3>
        <a class="btn-btn-btn" href="{% url 'usersapp:login' %}">Вхід</a>
    </div>
{% endblock %}

FishMarket/usersapp/templates/usersapp/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'usersapp:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

FishMarket/usersapp/templates/usersapp/profile.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'usersapp/css/form-control.css' %}">
    <script src="https://unpkg.com/imask"></script>
{% endblock %}
{% block section %}
    <section>
        <ul class="profile-elems">
            <li class="menu-elem">
                <ul>
                    <li class="active-link">
                        <img src="{% static 'usersapp/img/settings-profile.png' %}" alt="profile icon">
                        <a href="{% url 'usersapp:profile' %}">Профіль</a>
                    </li>
                    <li>
                        <img src="{% static 'img/history.png' %}" alt="profile icon">
                        <a href="#">Історія замовлень</a>
                    </li>
                    <li>
                        <img src="{% static 'img/address.png' %}" alt="profile icon">
                        <a href="#">Адреса доставки</a>
                    </li>
                    <li>
                        <img src="{% static 'usersapp/img/password.png' %}" alt="пароль">
                        <a href="{% url 'usersapp:password_change' %}">Змінити пароль</a>
                    </li>
                    <li class="exit-button">
                        <img src="{% static 'usersapp/img/exit.png' %}" alt="выхiд з аккаунту">
                        <a class='a-exit' href="{% url 'usersapp:logout' %}">Вийти з кабінету</a>
                    </li>
                </ul>
            </li>
            <li>
                <ul class="profile-menu">
                    <li>
                        <form class="form-user-data" method="POST" action="">
                            <h3 class="blue-bold-text">Моя інформація <br><span
                                    class="span-user-email">{{ user.email }}</span></h3>
                            {% csrf_token %}
                            {% for field in form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                            {% endfor %}

                            <button class='btn' type="submit">Обновить</button>
                        </form>
                    </li>
                </ul>
            </li>
            <li>
                <ul class="discount-container">
                    <li class="banner-discount-show">
                        <h3 class="white-bold-text">Моя знижка</h3>
                        <h3 class="span-user-discount">{{ user.discount }}%</h3>
                    </li>
                </ul>
            </li>
            <li>

            </li>
        </ul>
    </section>

    <script>
        const element = document.getElementById('phonenumber');
        const maskOptions = {
            mask: '+{38}(000)-000-00-00'
        };
        const mask = IMask(element, maskOptions);
    </script>

{% endblock %}